version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password ${{secrets.PTERODACTYL_MYSQL_PASSWORD}}
    MYSQL_ROOT_PASSWORD: ${{secrets.PTERODACTYL_MYSQL_ROOT_PASSWORD}}

  panel:
    &panel-environment
    APP_URL: "https://gs8.redgreenbird.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "media@rgbi.ch"
    TRUSTED_PROXIES: "*" # Set this to your proxy IP
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
    
  mail:
    &mail-environment
    MAIL_FROM: "noreply@rgbi.ch"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
      
  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
    links:
      - database
      - cache
    volumes:
      - data:/app/var/
      - data:/etc/nginx/http.d/
      - data:/etc/letsencrypt/
      - data:/app/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

  wings:
      image: ghcr.io/pterodactyl/wings:v1.6.1
      restart: always
      ports:
        - "8080:8080"
        - "2022:2022"
        - "9442:443"
      tty: true
      environment:
        TZ: "UTC"
        WINGS_UID: 988
        WINGS_GID: 988
        WINGS_USERNAME: pterodactyl
      volumes:
        - data:/var/run/docker.sock
        - data:/var/lib/docker/containers/
        - data:/etc/pterodactyl/
        - data:/var/lib/pterodactyl/
        - data:/var/log/pterodactyl/
        - data:/tmp/pterodactyl/
        - data:/etc/ssl/certs:ro
        # you may need /srv/daemon-data if you are upgrading from an old daemon
        #- "/srv/daemon-data/:/srv/daemon-data/"
        # Required for ssl if you use let's encrypt. uncomment to use.
        #- "/etc/letsencrypt/:/etc/letsencrypt/"

volumes:
  data:

# execute this command to create a user for the panel
# docker-compose run --rm panel php artisan p:user:mak